package online.monarchlabs.sentinel.assistant.audit;

public enum AuditStage {
    INPUT_RECEIVED,
    TEXT_NORMALIZED,
    INTENT_DETECTED,
    SLOTS_EXTRACTED,
    CONTEXT_RESOLVED,
    PLAN_CREATED,
    VALIDATION_FAILED,
    CONFLICT_DETECTED,
    CONFIRMATION_SHOWN,
    PARENT_CONFIRMED,
    COMMAND_CREATED,
    COMMAND_QUEUED,
    FIREBASE_WRITE_SUCCESS,
    FIREBASE_WRITE_FAILED,
    CHILD_RECEIVED,
    CHILD_APPLIED,
    CHILD_FAILED,
    UNDO_SNAPSHOT_CREATED,
    UNDO_EXECUTED
}
