package online.monarchlabs.sentinel.assistant.core;

public enum CommandType {
    ASSISTANT_BLOCK_APP,
    ASSISTANT_UNBLOCK_APP,
    ASSISTANT_UNBLOCK_ALL_APPS,
    ASSISTANT_BLOCK_CATEGORY,
    ASSISTANT_SET_APP_TIMER,
    ASSISTANT_REMOVE_APP_TIMER,
    ASSISTANT_PAUSE_RESTRICTIONS,
    ASSISTANT_RESUME_RESTRICTIONS,
    ASSISTANT_APPLY_TEMPLATE,
    ASSISTANT_ROLLBACK
}
