package online.monarchlabs.sentinel.assistant.core;

public enum ConflictType {
    DUPLICATE_RULE,
    BLOCK_OVERLAPS_ALLOW_RULE,
    TIMER_OVERLAPS_STRICTER_TIMER,
    UNBLOCK_BLOCKED_BY_HIGHER_PRIORITY,
    BEDTIME_OVERLAPS_STUDY_SCHEDULE,
    CATEGORY_BLOCK_CONFLICTS_WITH_EXCEPTION,
    ALL_APP_BLOCK_CONFLICTS_WITH_ALLOWED_APPS
}
